### ISSUE TITLE
How to install on Grafana Cloud

### ISSUE THREAD

**Issue by JacobArrow** [blackcowmoo/Grafana-Google-Analytics-DataSource#49]
I'm using Grafana Cloud and would like to know how I can install and use this plugin.
Can anyone help me?

**Comment by lcc3108** [comment]
Thank you for using the plugin.

Currently, we are waiting for a review to register with grafana community plugin.

After receiving the review once, I applied only the required modifications and submitted them on May 5th.

But I don't know when the review will be over.

When the review is end, it will be registered as a community plugin and can be use at grafana cloud
[download page](https://grafana.com/grafana/plugins/blackcowmoo-googleanalytics-datasource/?tab=installation) (not possible because it is currently under review)

**Comment by JacobArrow** [comment]
Thank you for the explanation. Please update this issue when then plugin has been accepted.

**Comment by itamarhaber** [comment]
@lcc3108 sounds amazing - looking forward to testing it there :)

**Comment by lcc3108** [comment]
I hope so, too.

I will share the plugin review result when it comes out.
